---
- hosts: test
  tasks:
  - name: Install Memcached
    yum: name=memcached,python-memcached state=present
  - name: Start the memcached service and configure it to start when the system boots
    service: name=memcached.service state=started enabled=yes
